### PR TITLE
More Secure Collection Id

### PR DESCRIPTION
**Pull request by h0ngcha0**
There is a corresponding [PR](https://github.com/alephium/alephium-web3/pull/265) for SDK. 

If the new interface methods look ok, will merge SDK and update this PR again.

### CODE REVIEW

**Review by Lbqds — APPROVED** [review]
LGTM

**Comment by polarker** [comment]
In `shared/nft.ts`, we use parentId for collection id, now we should remove that.

**Comment by h0ngcha0** [comment]
> In `shared/nft.ts`, we use parentId for collection id, now we should remove that.

Some NFTs might not have collection ids, but they still comply with the NFT interfaces (std id `#0003`), shall we fetch collection id from NFT directly and then fall back to parent if not available?

**Review by polarker — APPROVED** [review]
LGTM

**Pull request merged**
